### ISSUE TITLE
Registracion- Login de Usuario

### ISSUE THREAD

**Issue by MelisaVilar** [FSAgentesPublicos2022/grupo05-fsap2022-g05#1]
Como usuario quiero registrarme en la plataforma para pode hacer uso de la misma.

**Comment by danielaizquierdo** [comment]
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CRIPTOMONEDAS</title>  
</head>
<body>
 
  <fieldset> 
    <legend>REGISTRACI&Oacute;N</legend> 
    <label class="registraci&oacute;n" for="nombre">Nombre y Apellido</label>  
    <input id="nombre"><br>
    
    <label class="registraci&oacute;n" for="ID">DNI</label> 
    <input id="ID"><br> 
    
    <label class="telefono" for="telefono">Teléfono</label> 
    <input id="telefono" placeholder="xxx-xx-xx-xx"><br> 
    
    <label class="contacto" for="email">Email</label> 
    <input id="email" placeholder="ejemplo@correo.com"><br> 
  </fieldset>
</body>
</html>
