### ISSUE TITLE
US - Iniciar sesion

### ISSUE THREAD

**Issue by MelisaVilar** [FSAgentesPublicos2022/grupo05-fsap2022-g05#2]
Como usuario quiero iniciar sesión para comprar y vender criptomonedas.

**Comment by danielaizquierdo** [comment]
<form name="login" action="index_submit" method="get" accept-charset="utf-8">
    <ul>
      <li><label for="usermail">Correo electrónico</label>
      <input type="email" name="usermail" placeholder="tunombre@correoelectrónico.com" required></li>
      <li><label for="password">Contraseña</label>
      <input type="password" name="password" placeholder="contraseña" required></li>
      <li>
      <input type="submit" value="Login"></li>
    </ul>
  </form>
  </section>

**Comment by danielaizquierdo** [comment]
<form name="login" action="index_submit" method="get" accept-charset="utf-8">
    <ul>
      <li><label for="usermail">Correo electrónico</label>
      <input type="email" name="usermail" placeholder="tunombre@correoelectrónico.com" required></li>
      <li><label for="password">Contraseña</label>
      <input type="password" name="password" placeholder="contraseña" required></li>
      <li>
      <input type="submit" value="Login"></li>
    </ul>
  </form>
  </section>

**Comment by danielaizquierdo** [comment]
<form name="login" action="index_submit" method="get" accept-charset="utf-8">
    <ul>
      <li><label for="usermail">Correo electrónico</label>
      <input type="email" name="usermail" placeholder="tunombre@correoelectrónico.com" required></li>
      <li><label for="password">Contraseña</label>
      <input type="password" name="password" placeholder="contraseña" required></li>
      <li>
      <input type="submit" value="Login"></li>
    </ul>
  </form>
  </section>
